## Data Exploration  
The goal of this notebook is to get to know the data that will be used in this project.  

**Tasks:**  
1. Load Data
2. Explore/Clean Features

**1. Load Data**

In [4]:
import nflreadpy as nfl
import pandas as pd
import numpy as np

In [6]:
#only load a couple seasons to keep exploration fast
pbp = nfl.load_pbp([2022, 2024])

In [8]:
df = pbp.to_pandas()

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98926 entries, 0 to 98925
Columns: 372 entries, play_id to pass_oe
dtypes: float64(199), int32(8), object(165)
memory usage: 277.7+ MB

In [12]:
df.head()

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,None,None,None,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,43.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,0.0,1.0,-0.443521,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,68.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,0.0,1.0,1.468819,NaN,NaN,NaN,NaN,NaN,0.440373,-44.037291
3,89.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,0.0,1.0,-0.492192,0.727261,6.988125,6.0,0.60693,0.227598,0.389904,61.009598
4,115.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,0.0,1.0,-0.325931,NaN,NaN,NaN,NaN,NaN,0.443575,-44.357494

In [14]:
df.shape

(98926, 372)

**2. Data Exploration**

The idea behind this project is to build a model that acts as an offensive coordinator. Therefore, the model should only have access to data that an NFL OC would know in the moment. Therefore, we factor out unnecessary columns based on that. We also get rid of entries outside the scope of the model (special teams is an example).

In [18]:
df = df[
(df['play_type'].isin(['run', 'pass'])) & (df['special'] == 0) & (df['two_point_attempt'] == 0)
& (df['sack'] == 0) & (df['qb_scramble'] == 0)
]

In [20]:
df.shape

(65367, 372)

In [22]:
#building out our variable to be predicted by the model. Should be a play subtype ex: 'short pass left'
def classify_play(row):
    if row.play_type == 'run':
        if row.run_location == 'middle':
            return 'inside run'
        elif row.run_location in ['left', 'right']:
            return 'outside run'
    elif row.play_type == 'pass':
        if pd.notna(row.pass_length):
            return f"{row.pass_length} pass"
    return 'other'

df['play_subtype'] = df.apply(classify_play, axis=1)

In [23]:
df['play_subtype'].value_counts(dropna = False)

play_subtype
short pass     30722
outside run    20680
inside run      6989
deep pass       6724
other            252
Name: count, dtype: int64

In [24]:
df = df[df['play_subtype'] != 'other']

In [28]:
df['play_subtype'].value_counts(dropna = False)

play_subtype
short pass     30722
outside run    20680
inside run      6989
deep pass       6724
Name: count, dtype: int64

In [30]:
df['play_subtype'].count()

65115

In [32]:
df.shape

(65115, 373)

In [34]:
#Engineering Defensive Historical Features to help prediction in a realistic fashion

In [36]:
#Create new DataFrame that contains weekly defensive statistics for each team and season

In [38]:
df['rush_yards'] = df['yards_gained'].where(df['play_type'] == 'run')
df['is_pass'] = (df['play_type'] == 'pass').astype(int)

In [40]:
defsummary = (
    df.groupby(['defteam', 'season', 'week']).agg(
        avg_yds_allowed_per_play=('yards_gained', 'mean'),
        def_pass_rate=('is_pass', 'mean'),
        avg_rush_yds_allowed_play=('rush_yards', 'mean')
    )
    .reset_index()
)

In [42]:
defsummary = defsummary.sort_values(['defteam','season', 'week'])

In [48]:
grouped = defsummary.groupby(['defteam', 'season'])

defsummary[['def_pass_rate_rolling', 'avg_yds_pp_alwd_rolling', 'avg_rush_yds_pp_alwd_rolling']] = (
    grouped[['def_pass_rate', 'avg_yds_allowed_per_play', 'avg_rush_yds_allowed_play']]
    .shift(1)
    .rolling(3, min_periods = 1)
    .mean()
)

In [50]:
defsummary.head()

,defteam,season,week,avg_yds_allowed_per_play,def_pass_rate,avg_rush_yds_allowed_play,def_pass_rate_rolling,avg_yds_pp_alwd_rolling,avg_rush_yds_pp_alwd_rolling
0,ARI,2022,1,7.790323,0.629032,5.347826,NaN,NaN,NaN
1,ARI,2022,2,5.474576,0.661017,3.550000,0.629032,7.790323,5.347826
2,ARI,2022,3,8.261905,0.595238,5.764706,0.645025,6.632449,4.448913
3,ARI,2022,4,4.937500,0.750000,3.333333,0.628429,7.175601,4.887511
4,ARI,2022,5,5.287879,0.545455,3.666667,0.668752,6.224660,4.216013

In [42]:
defsummary['def_pass_rate_last3'] = (
    defsummary.groupby('defteam')['def_pass_rate']
        .shift(1)
        .rolling(3, min_periods = 1)
        .mean()
        .reset_index(level = 0, drop = True)
    )

In [44]:
defsummary['avg_yds_pp_alwd_last3'] = (
    defsummary.groupby('defteam')['avg_yds_allowed_per_play']
        .shift(1)
        .rolling(3, min_periods = 1)
        .mean()
        .reset_index(level = 0, drop = True)
    )

In [46]:
defsummary['avg_rush_pp_alwd_last3'] = (
    defsummary.groupby('defteam')['avg_rush_yds_allowed_play']
        .shift(1)
        .rolling(3, min_periods = 1)
        .mean()
        .reset_index(level = 0, drop = True)
    )

In [48]:
defsummary.head()

,defteam,season,week,avg_yds_allowed_per_play,def_pass_rate,avg_rush_yds_allowed_play,def_pass_rate_last3,avg_yds_pp_alwd_last3,avg_rush_pp_alwd_last3
0,ARI,2022,1,7.790323,0.629032,5.347826,NaN,NaN,NaN
1,ARI,2022,2,5.474576,0.661017,3.550000,0.629032,7.790323,5.347826
2,ARI,2022,3,8.261905,0.595238,5.764706,0.645025,6.632449,4.448913
3,ARI,2022,4,4.937500,0.750000,3.333333,0.628429,7.175601,4.887511
4,ARI,2022,5,5.287879,0.545455,3.666667,0.668752,6.224660,4.216013

In [50]:
df = df.merge(defsummary[['defteam', 'season', 'week', 'def_pass_rate_last3', 'avg_yds_pp_alwd_last3', 'avg_rush_pp_alwd_last3']],
              on = ['defteam', 'season', 'week'],
              how = 'left')

In [52]:
df.head()

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,xyac_success,xyac_fd,xpass,pass_oe,play_subtype,rush_yards,is_pass,def_pass_rate_last3,avg_yds_pp_alwd_last3,avg_rush_pp_alwd_last3
0,68.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,NaN,NaN,0.440373,-44.037291,outside run,19.0,0,0.656250,5.358173,4.320055
1,89.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,0.606930,0.227598,0.389904,61.009598,short pass,NaN,1,0.656250,5.358173,4.320055
2,115.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,NaN,NaN,0.443575,-44.357494,outside run,5.0,0,0.656250,5.358173,4.320055
3,136.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,NaN,NaN,0.963242,3.675753,short pass,NaN,1,0.656250,5.358173,4.320055
4,202.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,BAL,away,NYJ,...,0.606959,0.241949,0.479318,52.068213,short pass,NaN,1,0.488917,5.883399,3.732620

In [54]:
df = df[['season', 'week', 'game_id', 'posteam', 'defteam', 'qtr', 'down', 'ydstogo', 'yardline_100',
         'score_differential', 'def_pass_rate_last3', 'avg_yds_pp_alwd_last3', 'avg_rush_pp_alwd_last3',
         'play_subtype']]

In [56]:
df.head(20)

,season,week,game_id,posteam,defteam,qtr,down,ydstogo,yardline_100,score_differential,def_pass_rate_last3,avg_yds_pp_alwd_last3,avg_rush_pp_alwd_last3,play_subtype
0,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,1.0,10.0,78.0,0.0,0.656250,5.358173,4.320055,outside run
1,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,1.0,10.0,59.0,0.0,0.656250,5.358173,4.320055,short pass
2,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,2.0,10.0,59.0,0.0,0.656250,5.358173,4.320055,outside run
3,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,3.0,5.0,54.0,0.0,0.656250,5.358173,4.320055,short pass
4,2022,1,2022_01_BAL_NYJ,BAL,NYJ,1.0,1.0,10.0,72.0,0.0,0.488917,5.883399,3.732620,short pass
5,2022,1,2022_01_BAL_NYJ,BAL,NYJ,1.0,2.0,6.0,68.0,0.0,0.488917,5.883399,3.732620,short pass
6,2022,1,2022_01_BAL_NYJ,BAL,NYJ,1.0,3.0,2.0,64.0,0.0,0.488917,5.883399,3.732620,outside run
7,2022,1,2022_01_BAL_NYJ,BAL,NYJ,1.0,1.0,10.0,60.0,0.0,0.488917,5.883399,3.732620,outside run
8,2022,1,2022_01_BAL_NYJ,BAL,NYJ,1.0,2.0,10.0,60.0,0.0,0.488917,5.883399,3.732620,short pass
9,2022,1,2022_01_BAL_NYJ,BAL,NYJ,1.0,3.0,2.0,52.0,0.0,0.488917,5.883399,3.732620,outside run
10,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,1.0,10.0,89.0,0.0,0.656250,5.358173,4.320055,outside run
11,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,2.0,12.0,91.0,0.0,0.656250,5.358173,4.320055,short pass
12,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,1.0,10.0,83.0,0.0,0.656250,5.358173,4.320055,inside run
13,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,2.0,9.0,82.0,0.0,0.656250,5.358173,4.320055,outside run
14,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,3.0,9.0,82.0,0.0,0.656250,5.358173,4.320055,deep pass
15,2022,1,2022_01_BAL_NYJ,BAL,NYJ,1.0,1.0,10.0,66.0,0.0,0.488917,5.883399,3.732620,short pass
16,2022,1,2022_01_BAL_NYJ,BAL,NYJ,1.0,2.0,10.0,66.0,0.0,0.488917,5.883399,3.732620,inside run
17,2022,1,2022_01_BAL_NYJ,BAL,NYJ,1.0,3.0,9.0,65.0,0.0,0.488917,5.883399,3.732620,short pass
18,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,1.0,10.0,83.0,0.0,0.656250,5.358173,4.320055,deep pass
19,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,1.0,10.0,59.0,0.0,0.656250,5.358173,4.320055,outside run

In [31]:
df.isnull().sum()

season                     0
week                       0
game_id                    0
posteam                    0
defteam                    0
qtr                        0
down                       0
ydstogo                    0
yardline_100               0
score_differential         0
def_pass_rate_last3       62
avg_yds_pp_alwd_last3     62
avg_rush_pp_alwd_last3    62
play_subtype               0
dtype: int64

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65115 entries, 0 to 65114
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   season                  65115 non-null  int32
 1   week                    65115 non-null  int32
 2   game_id                 65115 non-null  object
 3   posteam                 65115 non-null  object
 4   defteam                 65115 non-null  object
 5   qtr                     65115 non-null  float64
 6   down                    65115 non-null  float64
 7   ydstogo                 65115 non-null  float64
 8   yardline_100            65115 non-null  float64
 9   score_differential      65115 non-null  float64
 10  def_pass_rate_last3     65053 non-null  float64
 11  avg_yds_pp_alwd_last3   65053 non-null  float64
 12  avg_rush_pp_alwd_last3  65053 non-null  float64
 13  play_subtype            65115 non-null  object
dtypes: float64(8), int32(2), object(4)
memory usage: 6.5+ MB

In [32]:
df.shape

(65115, 14)

There are going to be some null values in these historical aggregate columns. This is due to the fact that this model considers prior games up to the start of the season. So there are not always enough games to have a historical average. Because of this, we will drop null values for simplicity and ease of modeling.

In [34]:
df = df.dropna()

In [35]:
df.isnull().sum()

season                    0
week                      0
game_id                   0
posteam                   0
defteam                   0
qtr                       0
down                      0
ydstogo                   0
yardline_100              0
score_differential        0
def_pass_rate_last3       0
avg_yds_pp_alwd_last3     0
avg_rush_pp_alwd_last3    0
play_subtype              0
dtype: int64

In [36]:
df.shape

(65053, 14)

In [37]:
df.head()

,season,week,game_id,posteam,defteam,qtr,down,ydstogo,yardline_100,score_differential,def_pass_rate_last3,avg_yds_pp_alwd_last3,avg_rush_pp_alwd_last3,play_subtype
0,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,1.0,10.0,78.0,0.0,0.656250,5.358173,4.320055,outside run
1,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,1.0,10.0,59.0,0.0,0.656250,5.358173,4.320055,short pass
2,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,2.0,10.0,59.0,0.0,0.656250,5.358173,4.320055,outside run
3,2022,1,2022_01_BAL_NYJ,NYJ,BAL,1.0,3.0,5.0,54.0,0.0,0.656250,5.358173,4.320055,short pass
4,2022,1,2022_01_BAL_NYJ,BAL,NYJ,1.0,1.0,10.0,72.0,0.0,0.488917,5.883399,3.732620,short pass

This is where I want the data to be after cleaning and preprocessing. Next steps will be to explore the modeling process of this project (see 02_modeling.ipynb) to ensure that no further preprocessing needs to be done. Eventually the steps taken in this notebook to preprocess data will be ported to C++ for efficiency.

In [39]:
df.to_csv('cleaned_pbp_22_to_24.csv', index=False)